### PR TITLE
Customized increments arrows

### PR DESCRIPTION
**Pull request by Anthony-one**

### CODE REVIEW

**Comment by b0bdN** [comment]
Thanks!
Do you think it's possible to change the color in dark mode ?

**Comment by Anthony-one** [comment]
Hmmm from what i understand we cannot change the color of the button itself, at best i tested reducing the opacity of the button only in dark mode so it can look better.
Capture d’écran 2022-03-14 025930
What do you think?

**Comment by b0bdN** [comment]
It's perfect! :)
Can you move this code in it's on block in line 425 in order in order to avoid modifying twice in light and dark mode?
```css
padding-left: 5px;
height: 30px;
```

**Comment by Anthony-one** [comment]
Sure done :)

**Comment by b0bdN** [comment]
Thank you!

**Pull request merged**
